server:
  port: 8240
spring:
  http:
    encoding:
      enabled: true
  datasource:
    url: jdbc:mysql://10.10.31.26:3306/iv_ops_shared?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123@abcd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.connection.url: jdbc:mysql://10.10.31.26:3306/iv_ops_shared?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: root
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.event.merge.entity_copy_observer: allow      

    
      