eureka:
  instance:
    status-page-url: http://10.10.9.26:${server.port}/swagger-ui.html
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000 
spring:
  profiles:
    active:
    - dev-peer1
  application:
    name: alarm-strategy-service
  http:
    encoding:
      enabled: true
  datasource:
    url: jdbc:mysql://10.10.31.25:3306/alarm_strategy_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123@abcd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database: mysql
      database-platform: mysql
      show-sql: false
      hibernate:
        ddl-auto: update
        naming:
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      properties:
        hibernate.connection.url: jdbc:mysql://10.10.31.25:3306/alarm_strategy_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        hibernate.connection.username: root
        hibernate.hbm2ddl.auto: update
        hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.event.merge.entity_copy_observer: allow
        #------------------------以下多租户配置属性---------------------------#
        hibernate.multiTenancy: SCHEMA
        hibernate.tenant_identifier_resolver: com.iv.strategy.util.TenantIdResolver
        hibernate.multi_tenant_connection_provider: com.iv.strategy.util.MultiTenantConnectionProviderImpl
        hibernate.connection.password: 123@abcd
        hibernate.connection.driver_class: com.mysql.jdbc.Driver
        hibernate.c3p0.minPoolSize: 5
        hibernate.c3p0.maxIdleTime: 120
        hibernate.c3p0.idleConnectionTestPeriod: 18000

#-----多环境支持配置-----#
#开发环境#
---
server:
  port: 8440
spring:
  profiles: dev-peer1
    
---
server:
  port: 8441
spring:
  profiles: dev-peer2
  
#生产环境#  
---
eureka:
  instance:
    status-page-url: http://${spring.application.name}:${server.port}/swagger-ui.html
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ivops:123abcd@eureka-server:8110/eureka/
server:
  port: 8440
spring:
  profiles: product-peer1
  datasource:
    url: jdbc:mysql://aggregation_db:3306/alarm_strategy_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ivops
#------------------------以下多租户配置属性---------------------------#
  jpa:
    properties:
      hibernate.connection.url: jdbc:mysql://aggregation_db:3306/alarm_strategy_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: ivops
logging:
   file: /opt/ivops/logs/alarm-strategy-service-peer1.log
   
---
eureka:
  instance:
    status-page-url: http://${spring.application.name}:${server.port}/swagger-ui.html
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ivops:123abcd@eureka-server:8110/eureka/
server:
  port: 8441
spring:
  profiles: product-peer2
  datasource:
    url: jdbc:mysql://aggregation_db:3306/alarm_strategy_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ivops
#------------------------以下多租户配置属性---------------------------#
  jpa:
    properties:
      hibernate.connection.url: jdbc:mysql://aggregation_db:3306/alarm_strategy_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: ivops
logging:
   file: /opt/ivops/logs/alarm-strategy-service-peer2.log