server:
  context-path: /uaa
  
eureka:
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
    
spring:
  profiles:
    active:
    - peer1
  application:
    name: authentication-server
feign:
  hystrix:
    enabled: true    
logging:
  level:
    org.springframework : DEBUG
#logging:
#  level:
#    org.springframework : DEBUG
#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: secret
#      access-token-validity-seconds: 3600
#      refresh-token-validity-seconds: 3600
#自定义变量
#iv:
#  web:
#    loginPage: http://10.10.9.25:7100/login
   
---
spring:
  profiles: peer1
server:
  port: 8210
  
---
spring:
  profiles: peer1
server:
  port: 8211

  
      