eureka:
  instance:
    status-page-url: http://10.10.9.55:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
spring:
  profiles:
    active:
    - peer1
  application:
    name: group-service
  http:
    encoding:
      enabled: true
  datasource:
    url: jdbc:mysql://10.10.31.26:3306/group_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123@abcd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.connection.url: jdbc:mysql://10.10.31.26:3306/group_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: root
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.event.merge.entity_copy_observer: allow
      #------------------------以下多租户配置属性---------------------------#
      hibernate.multiTenancy: SCHEMA
      hibernate.tenant_identifier_resolver: com.iv.group.util.TenantIdResolver
      hibernate.multi_tenant_connection_provider: com.iv.group.util.MultiTenantConnectionProviderImpl
      hibernate.connection.password: 123@abcd
      hibernate.connection.driver_class: com.mysql.jdbc.Driver
      hibernate.c3p0.minPoolSize: 5
      hibernate.c3p0.maxIdleTime: 120
      hibernate.c3p0.idleConnectionTestPeriod: 18000
security:
  basic:
    enabled: false
---
server:
  port: 8280
spring:
  profiles: peer1
---
server:
  port: 8281
spring:
  profiles: peer2
  
#生产环境#  
---
server:
  port: 8280
spring:
  profiles: product-peer1
  datasource:
    url: jdbc:mysql://db.mas.ivops:3280/group_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: mas
  #------------------------以下多租户配置属性---------------------------#
  jpa:
    properties:
      hibernate.connection.url: jdbc:mysql://db.mas.ivops:3280/group_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: mas
logging:
  file: /var/log/ivops/group/group-service/peer1/group-service.log
   
---
server:
  port: 8281
spring:
  profiles: product-peer2
  datasource:
    url: jdbc:mysql://db.mas.ivops:3280/group_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: mas
  #------------------------以下多租户配置属性---------------------------#
  jpa:
    properties:
      hibernate.connection.url: jdbc:mysql://db.mas.ivops:3280/group_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: mas
logging:
  file: /var/log/ivops/group/group-service/peer2/group-service.log

      
