eureka:
  instance:
    status-page-url: http://10.10.9.26:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
feign:
  hystrix:
    enabled: true
security:
  basic:
    enabled: false
spring:
  profiles:
    active:
    - dev-peer1
  application:
    name: alarm-facade-service
  http:
    encoding:
      enabled: true

#-----多环境支持配置-----#
#开发环境#
---
server:
  port: 8420
spring:
  profiles: dev-peer1
    
---
server:
  port: 8421
spring:
  profiles: dev-peer2
  
#生产环境#  
---
server:
  port: 8420
spring:
  profiles: product-peer1
logging:
   file: /var/log/ivops/alarm/alarm-facade-service/peer1/alarm-facade-service.log
   
---
server:
  port: 8421
spring:
  profiles: product-peer2
logging:
   file: /var/log/ivops/alarm/alarm-facade-service/peer2/alarm-facade-service.log