package com.iv.message.api.constant;

public enum MsgType {

	ALARM_TRIGGER, ALARM_RECOVERY, TNT_NEW_PENDING, TNT_NEW_RESULT, TNT_JOIN_PENDING, 
	
	TNT_JOIN_RESULT, FORM_PENDING, FORM_REVIEW, FORM_EVALUATE,
	
	SCRIPT_NEW_PENDING, SCRIPT_NEW_RESULT;
}
