eureka:
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
spring:
  profiles:
    active:
    - peer1
  application:
    name: zuul-service
zuul:
  prefix: /v1
  sensitive-headers: Cookie,Set-Cookie
  routes:
    api-1:
      path: /user/**
      serviceId: user-service
    api-2:
      path: /wechat/**
      serviceId: wechat-service
    api-3:
      path: /alarm/aggregation/**
      serviceId: alarm-aggregation-service
    api-4:
      path: /alarm/facade/**
      serviceId: alarm-facade-service
    api-5:
      path: /alarm/strategy/**
      serviceId: alarm-strategy-service
    api-6:
      path: /tenant/mgt/**
      serviceId: tenant-mgt-service
    api-7:
      path: /email/**
      serviceId: email-service
    api-8:
      path: /group/**
      serviceId: group-service
    api-9:
      path: /message/**
      service-id: message-service
    api-10:
      path: /alarm/report/**
      service-id: alarm-report-service
    api-11:
      path: /authentication/**
      service-id: authentication-server

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 1

#jwt oauth2
security:
#  basic:
#    enabled: false
  oauth2:
#    authorization:
#      realm: Authorization
#    sso:
#      login-path: /login
    client:
      access-token-uri: http://authentication-server/uaa/oauth/token
      user-authorization-uri: http://authentication-server/uaa/oauth/authorize
      client-id: client
      client-secret: secret
      grant-type: password
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAurW7iiT3kzvj159Ji9kHuOAgYrlSbCjfsICwKmQYCu6Zqp13c3nn8ZQvvMRrVouXoiRAvSxkO6X1rT4PaLSDTxlIcLG2tYL5Q7yRG8fBlweNS1YbYKzglTEdw9SkTR7UlJW1i/Sp6hIrGv+DH4YEQs1eXFPCRDrLXN+Tze6zwmUv0u/kfIp1yZoYQuB/ZNy/K9w4+f/gHCiJ7gCmU6PibkTxDsdJRC4X7V5lKmZ9LfzOaXB7trsFRHXov459dIwAypE4Zyf3O79/dDHkm84HKehMAPD8GjCyByzD1BZQ5g4H2PdZPvGwTqOjylyZa1HsqE9UeKoGOKOxMkAGXcG/hQIDAQAB
          -----END PUBLIC KEY-----
      id: zuul
      service-id: ${PREFIX:}zuul
logging:
  level:
    org.springframework : DEBUG
---
spring:
  profiles: peer1
server:
  port: 8120

---
spring:
  profiles: peer2
server:
  port: 8121