eureka:       
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
  instance:
    prefer-ip-address: true
    status-page-url: http://10.10.9.13:${server.port}/swagger-ui.html
spring:
  profiles:
    active:
    - peer1
  application:
    name: zuul-service
  http:
    encoding:
      enabled: true
  #redis连接
  redis:
    host: 10.10.31.25
    database: 2
    port: 6379
    password: 123@abcd
    timeout: 5000
    pool:
      max-active: 50
      max-idle: 20
      max-wait: -1
      min-idle: 0



zuul:
  servlet-path: /
  prefix: /v1
  sensitive-headers: Cookie,Set-Cookie
  routes:
    api-1:
      path: /user/**
      serviceId: user-service
    api-2:
      path: /wechat/**
      serviceId: wechat-service
    api-3:
      path: /alarm/aggregation/**
      serviceId: alarm-aggregation-service
    api-4:
      path: /alarm/facade/**
      serviceId: alarm-facade-service
    api-5:
      path: /alarm/strategy/**
      serviceId: alarm-strategy-service
    api-6:
      path: /tenant/mgt/**
      serviceId: tenant-mgt-service
    api-7:
      path: /email/**
      serviceId: email-service
    api-8:
      path: /group/**
      serviceId: group-service
    api-9:
      path: /message/**
      service-id: message-service
    api-10:
      path: /alarm/report/**
      service-id: alarm-report-service
    api-11:
      path: /authentication/**
      service-id: authentication-server
    api-12:
      path: /form/**
      service-id: form-service
    api-13:
      path: /script/**
      service-id: script-service
    api-14:
      path: /permission/**
      service-id: permission-service
    api-15:
      path: /operation/script/**
      service-id: operation-script-service
    api-16:
      path: /operation/vsphere/**
      service-id: operation-vsphere-service
    api-17:
      path: /resource/**
      service-id: resource-service
    api-18:
      path: /operation/db/**
      service-id: operation-db-service

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  MaxAutoRetries: 3
  MaxAutoRetriesNextServer: 1
  
iv:
  public:
    uris: /v1/wechat/**,
          /v1/logout,
          /v1/authentication/uaa/**,
          /v1/uaa/**,
          /v1/alarm/aggregation/openalarm,
          /v1/user/bind/wechatInfo,
          /v1/user/register/account,
          /v1/user/get/token,
          /swagger-ui.html,
          /swagger-resources/**,
          /v1/operation/script/**,
          /v1/alarm/facade/**,
          /v1/wechat/**,
          /v1/alarm/report/**,
          /v1/operation/db/**,
          /v1/form/select/formByCallBack,
          /v1/script/official/read,
          /v1/script/temp/read
          

  noAuthentication:
    uris: /v1/authentication/**,
          /v1/form/select/formListPage,
          /v1/form/select/formById,
          /v1/form/select/myFormListPage,
          /v1/form/select/delFormListPage,
          /v1/form/save/MarkForm,
          /v1/form/del/MarkForm,
          /v1/form/select/currentForm,
          /v1/form/select/dataCollection,
          /v1/form/select/pieChartByKind,
          /v1/form/select/groupAndClients,
          /v1/form/select/companyInfoList,
          /v1/form/select/conditionInfoList,
          /v1/form/select/formPullDown,
          /v1/form/select/demandTree,
          /v1/form/select/engineerList,
          /v1/form/select/formTrend,
          /v1/form/downloadFile,
          /v1/form/uploadFile,
          /v1/form/del/file,
          /v1/group/**,
          /v1/email/**,
          /v1/tenant/**,
          /v1/alarm/**,
          /v1/user/**,
          /v1/wechat/**,
          /v1/permission/**



#jwt oauth2
security:
#  basic:
#    enabled: false
  oauth2:
#    authorization:
#      realm: Authorization
#    sso:
#      login-path: /login
    client:
      access-token-uri: http://authentication-server/uaa/oauth/token
      user-authorization-uri: http://authentication-server/uaa/oauth/authorize
      client-id: client
      client-secret: secret
      grant-type: password
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAurW7iiT3kzvj159Ji9kHuOAgYrlSbCjfsICwKmQYCu6Zqp13c3nn8ZQvvMRrVouXoiRAvSxkO6X1rT4PaLSDTxlIcLG2tYL5Q7yRG8fBlweNS1YbYKzglTEdw9SkTR7UlJW1i/Sp6hIrGv+DH4YEQs1eXFPCRDrLXN+Tze6zwmUv0u/kfIp1yZoYQuB/ZNy/K9w4+f/gHCiJ7gCmU6PibkTxDsdJRC4X7V5lKmZ9LfzOaXB7trsFRHXov459dIwAypE4Zyf3O79/dDHkm84HKehMAPD8GjCyByzD1BZQ5g4H2PdZPvGwTqOjylyZa1HsqE9UeKoGOKOxMkAGXcG/hQIDAQAB
          -----END PUBLIC KEY-----
      id: zuul
      service-id: ${PREFIX:}zuul
#logging:
#  level:
#    org.springframework : DEBUG
---
spring:
  profiles: peer1
server:
  port: 8120

---
spring:
  profiles: peer2
server:
  port: 8121
  
#生产环境
---
eureka:
  instance:
    status-page-url: http://${spring.application.name}:${server.port}/swagger-ui.html
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ivops:123abcd@eureka-server:8110/eureka/
spring:
  profiles: product-peer1
server:
  port: 8120
logging:
   file: /var/log/ivops/zuul-service/peer1/zuul-service.log
   
---
eureka:
  instance:
    status-page-url: http://${spring.application.name}:${server.port}/swagger-ui.html
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ivops:123abcd@eureka-server:8110/eureka/
spring:
  profiles: product-peer2
server:
  port: 8121
logging:
   file: /var/log/ivops/zuul-service/peer2/zuul-service.log