eureka:
  instance:
    prefer-ip-address: true
    status-page-url: http://10.10.9.26:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
security:
  basic:
    enabled: false
feign:
  hystrix:
    enabled: true
spring:
  profiles:
    active:
    - dev-peer1
  application:
    name: operation-script-service
  http:
    encoding:
      enabled: true
  datasource:
    name: operation_script_service
    url: jdbc:mysql://10.10.31.25:3306/operation_script_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123@abcd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
      database: mysql
      database-platform: mysql
      show-sql: false
      hibernate:
        ddl-auto: update
        naming:
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      properties:
        hibernate.connection.url: jdbc:mysql://10.10.31.25:3306/operation_script_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        hibernate.connection.username: root
        hibernate.hbm2ddl.auto: update
        hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate.event.merge.entity_copy_observer: allow
        #------------------------以下多租户配置属性---------------------------#
        hibernate.multiTenancy: SCHEMA
        hibernate.tenant_identifier_resolver: com.iv.operation.script.util.TenantIdResolver
        hibernate.multi_tenant_connection_provider: com.iv.operation.script.util.MultiTenantConnectionProviderImpl
        hibernate.connection.password: 123@abcd
        hibernate.connection.driver_class: com.mysql.jdbc.Driver
        hibernate.c3p0.minPoolSize: 5
        hibernate.c3p0.maxIdleTime: 120
        hibernate.c3p0.idleConnectionTestPeriod: 18000
  devtools:
    restart:
      enabled: false

logging:
  level:
    root: info
  file: E:\workspace\mas.log
  
#自定义变量#



#-----多环境支持配置-----#
#开发环境#
---
server:
  port: 9020
spring:
  profiles: dev-peer1
    
---
server:
  port: 9021
spring:
  profiles: dev-peer2

#生产环境#  
---
server:
  port: 9020
spring:
  profiles: product-peer1
  datasource:
    url: jdbc:mysql://db.mas.ivops:3306/operation_script_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: mas
  #------------------------以下多租户配置属性---------------------------#
  jpa:
    properties:
      hibernate.connection.url: jdbc:mysql://db.mas.ivops:3306/operation_script_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: mas
logging:
  file: /var/log/ivops/operation/script/operation-script-service/peer1/operation-script-service.log
   
---
server:
  port: 9021
spring:
  profiles: product-peer2
  datasource:
    url: jdbc:mysql://db.mas.ivops:3306/operation_script_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: mas
  #------------------------以下多租户配置属性---------------------------#
  jpa:
    properties:
      hibernate.connection.url: jdbc:mysql://db.mas.ivops:3306/operation_script_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: mas
logging:
  file: /var/log/ivops/operation/script/operation-script-service/peer1/operation-script-service.log