server:
  context-path: /uaa
  
eureka:
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
spring:
  profiles:
    active:
    - peer1
  application:
    name: authentication-server
  #redis连接
  redis:
    host: 10.10.31.25
    database: 2
    port: 6379
    password: 123@abcd
    timeout: 5000
    pool:
      max-active: 50
      max-idle: 20
      max-wait: -1
      min-idle: 0
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000    
#logging:
#  level:
#    org.springframework : DEBUG
#logging:
#  level:
#    org.springframework : DEBUG
#security:
#  oauth2:
#    client:
#      client-id: client
#      client-secret: secret
#      access-token-validity-seconds: 3600
#      refresh-token-validity-seconds: 3600
#自定义变量
#iv:
#  web:
#    loginPage: http://10.10.9.25:7100/login

iv:
  redis:
    expireTime: 12

---
spring:
  profiles: peer1
server:
  port: 8210
  
---
spring:
  profiles: peer1
server:
  port: 8211

#生产环境
---
eureka:
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
  instance:
    ip-address: authentication
    hostname: authentication
spring:
  profiles: product-peer1
server:
  port: 8210
  
---
eureka:
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
spring:
  profiles: product-peer2
server:
  port: 8211