eureka:
  instance:
    status-page-url: http://10.10.9.13:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.21:8110/eureka/
spring:
  profiles:
    active:
    - dev-peer1
  application:
    name: form-service
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  datasource:
    url: jdbc:mysql://10.10.31.25:3306/form_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123@abcd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    database-platform: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate.connection.url: jdbc:mysql://10.10.31.25:3306/user_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: root
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.event.merge.entity_copy_observer: allow
      #------------------------以下多租户配置属性---------------------------#
      hibernate.multiTenancy: SCHEMA
      hibernate.tenant_identifier_resolver: com.iv.form.config.TenantIdResolver
      hibernate.multi_tenant_connection_provider: com.iv.form.config.MultiTenantConnectionProviderImpl
      hibernate.connection.password: 123@abcd
      hibernate.connection.driver_class: com.mysql.jdbc.Driver
      hibernate.c3p0.minPoolSize: 5
      hibernate.c3p0.maxIdleTime: 120
      hibernate.c3p0.idleConnectionTestPeriod: 18000

  activiti:
    check-process-definitions: false

security:
  basic:
    enabled: false
feign:
  hystrix:
    enabled: true

logging:
  file: E:\workspace\mas.log
  level: debug

#自定义变量#
iv:
  upload:
    savePath: E:\upload\form\
    #设置上传单个文件的大小的最大值，目前是设置为1024*1024字节，也就是1MB
    fileSizeMax: 1048576
    #设置上传文件总量的最大值，最大值=同时上传的多个文件的大小的最大值的和，目前设置为10MB
    sizeMax: 10485760
  wechat:
    redirectUri: http://2038b2u538.iok.la/static/order/detail/



---
server:
  port: 9010
spring:
  profiles: dev-peer1

---
server:
  port: 9011
spring:
  profiles: dev-peer2


#生产环境#
---
server:
  port: 9010
eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.42:8110/eureka/

spring:
  profiles: product-peer1
  datasource:
    url: jdbc:mysql://form_db:3306/form_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ivops
    password: 123@abcd
  jpa:
    properties:
      hibernate.connection.url: jdbc:mysql://form_db:3306/form_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: ivops
      hibernate.connection.password: 123@abcd
logging:
   file: /opt/ivops/ops/form-service-peer1.log
   level: debug

iv:
  upload:
    savePath: /opt/ivops/storage/form

---
server:
  port: 9011
eureka:
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    service-url:
      defaultZone: http://ivops:123abcd@10.10.31.42:8110/eureka/

spring:
  profiles: product-peer2
  datasource:
    url: jdbc:mysql://form_db:3306/form_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: ivops
    password: 123@abcd
  jpa:
    properties:
      hibernate.connection.url: jdbc:mysql://form_db:3306/form_service?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      hibernate.connection.username: ivops
      hibernate.connection.password: 123@abcd
logging:
   file: /opt/ivops/ops/form-service-peer2.log
   level: debug

iv:
  upload:
    savePath: /opt/ivops/storage/form
